<a href="https://colab.research.google.com/github/Otobi1/Fuel-Effficiency-Prediction-End-to-End/blob/master/End_to_End_MPG_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Data Preparation 

"""
Handling Categorical Attribute - OneHotEncoder,
Data Cleaning - Imputer, 
Attribute Addition - Adding Custome Transformation, 
Setting up Data Transformation Pipeline for Numerical and Categorical Variables
"""

'\nHandling Categorical Attribute - OneHotEncoder,\nData Cleaning - Imputer, \nAttribute Addition - Adding Custome Transformation, \nSetting up Data Transformation Pipeline for Numerical and Categorical Variables\n'

In [ ]:
# Importing the necessary libraries 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

from sklearn.model_selection import StratifiedShuffleSplit

import warnings
warnings.filterwarnings("ignore")

In [ ]:
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data

--2020-11-10 19:00:54--  http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30286 (30K) [application/x-httpd-php]
Saving to: ‘auto-mpg.data.2’

auto-mpg.data.2     100%[===================>]  29.58K  --.-KB/s    in 0.06s   

2020-11-10 19:00:54 (465 KB/s) - ‘auto-mpg.data.2’ saved [30286/30286]



In [ ]:
# Reading the .data file using pandas

cols = ["MPG", "Cylinders", "Displacement", "Horsepower", "Weight", "Acceleration", "Model Year", "Origin"]

df = pd.read_csv("./auto-mpg.data", names = cols, na_values = "?", comment = "\t", sep = " ", skipinitialspace = True)

data = df.copy()

split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)
for train_index, test_index in split.split(data, data["Cylinders"]):
  strat_train_set = data.loc[train_index]
  strat_test_set = data.loc[test_index]

In [ ]:
# Separating the Target and the Feature Variables 

data = strat_train_set.drop("MPG", axis = 1)
data_labels = strat_train_set["MPG"].copy()
data

Cylinders  Displacement  Horsepower  ...  Acceleration  Model Year  Origin
145          4          83.0        61.0  ...          19.0          74       3
151          4          79.0        67.0  ...          16.0          74       2
388          4         156.0        92.0  ...          14.5          82       1
48           6         250.0        88.0  ...          14.5          71       1
114          4          98.0        90.0  ...          15.5          73       2
..         ...           ...         ...  ...           ...         ...     ...
147          4          90.0        75.0  ...          15.5          74       2
156          8         400.0       170.0  ...          11.5          75       1
395          4         135.0        84.0  ...          11.6          82       1
14           4         113.0        95.0  ...          15.0          70       3
362          6         146.0       120.0  ...          13.8          81       3

[318 rows x 7 columns]

In [ ]:
# Preprocessing the Origin Column

def preprocess_origin_cols(df):
  df["Origin"] = df["Origin"].map({1: "India", 2: "USA", 3: "Germany"})
  return df 
data_tr = preprocess_origin_cols(data)
data_tr.head()

Cylinders  Displacement  Horsepower  ...  Acceleration  Model Year   Origin
145          4          83.0        61.0  ...          19.0          74  Germany
151          4          79.0        67.0  ...          16.0          74      USA
388          4         156.0        92.0  ...          14.5          82    India
48           6         250.0        88.0  ...          14.5          71    India
114          4          98.0        90.0  ...          15.5          73      USA

[5 rows x 7 columns]

In [ ]:
# One Hot Encoding the Origin Column 

data_tr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 318 entries, 145 to 362
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Cylinders     318 non-null    int64  
 1   Displacement  318 non-null    float64
 2   Horsepower    314 non-null    float64
 3   Weight        318 non-null    float64
 4   Acceleration  318 non-null    float64
 5   Model Year    318 non-null    int64  
 6   Origin        318 non-null    object 
dtypes: float64(4), int64(2), object(1)
memory usage: 19.9+ KB


In [ ]:
# Isolating the Origin COlumn 

data_cat = data_tr[["Origin"]]
data_cat.head()

Origin
145  Germany
151      USA
388    India
48     India
114      USA

In [ ]:
#onehotencoding the categorical values 

from sklearn.preprocessing import OneHotEncoder

cat_encoder = OneHotEncoder()
data_cat_1hot = cat_encoder.fit_transform(data_cat)
data_cat_1hot # returns a sparse matrix (several columns based on the number of classes of the categorical variables)

<318x3 sparse matrix of type '<class 'numpy.float64'>'
	with 318 stored elements in Compressed Sparse Row format>

In [ ]:
data_cat_1hot.toarray()[:5]

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
cat_encoder.categories_

[array(['Germany', 'India', 'USA'], dtype=object)]

In [ ]:
# Handling Missing Values using Simple Imputer - Separating the numerical columns 

num_data = data.iloc[:, :-1]
num_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 318 entries, 145 to 362
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Cylinders     318 non-null    int64  
 1   Displacement  318 non-null    float64
 2   Horsepower    314 non-null    float64
 3   Weight        318 non-null    float64
 4   Acceleration  318 non-null    float64
 5   Model Year    318 non-null    int64  
dtypes: float64(4), int64(2)
memory usage: 17.4 KB


In [ ]:
# Handling missing values 

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = "median")
imputer.fit(num_data)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='median', verbose=0)

In [ ]:
# median of all the columns from imputer 

imputer.statistics_

array([   4. ,  146. ,   92. , 2844. ,   15.5,   76. ])

In [ ]:
#median from pandas dataframe

data.median().values 

array([   4. ,  146. ,   92. , 2844. ,   15.5,   76. ])

In [ ]:
# imputing the missing values by transforming the dataframe

X = imputer.transform(num_data)
X

array([[   4. ,   83. ,   61. , 2003. ,   19. ,   74. ],
       [   4. ,   79. ,   67. , 2000. ,   16. ,   74. ],
       [   4. ,  156. ,   92. , 2585. ,   14.5,   82. ],
       ...,
       [   4. ,  135. ,   84. , 2295. ,   11.6,   82. ],
       [   4. ,  113. ,   95. , 2372. ,   15. ,   70. ],
       [   6. ,  146. ,  120. , 2930. ,   13.8,   81. ]])

In [ ]:
# converting the 2D array back into dataframe 

data_tr = pd.DataFrame(X, columns = num_data.columns, index = num_data.index)

data_tr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 318 entries, 145 to 362
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Cylinders     318 non-null    float64
 1   Displacement  318 non-null    float64
 2   Horsepower    318 non-null    float64
 3   Weight        318 non-null    float64
 4   Acceleration  318 non-null    float64
 5   Model Year    318 non-null    float64
dtypes: float64(6)
memory usage: 17.4 KB


In [ ]:
# Adding Attributes using  BaseEstimator and Transformer

num_data.head()

Cylinders  Displacement  Horsepower  Weight  Acceleration  Model Year
145          4          83.0        61.0  2003.0          19.0          74
151          4          79.0        67.0  2000.0          16.0          74
388          4         156.0        92.0  2585.0          14.5          82
48           6         250.0        88.0  3139.0          14.5          71
114          4          98.0        90.0  2265.0          15.5          73

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin

acc_ix, hpower_ix, cyl_ix = 4, 2, 0

class CustomAttrAdder(BaseEstimator, TransformerMixin):
  def __init__(self, acc_on_power = True): # no *args or **kargs
    self.acc_on_power = acc_on_power
  def fit(self, X, y = None):
    return self # nothing else to do
  def transform(self, X): 
    acc_on_cyl = X[:, acc_ix] / X[:, cyl_ix]
    if self.acc_on_power: 
      acc_on_power = X[:, acc_ix] / X[:, hpower_ix]
      return np.c_[X, acc_on_power, acc_on_cyl]

    return np.c_[X, acc_on_cyl]

attr_adder = CustomAttrAdder(acc_on_power = True)
data_tr_extra_attrs = attr_adder.transform(data_tr.values)
data_tr_extra_attrs[0]


array([4.0000000e+00, 8.3000000e+01, 6.1000000e+01, 2.0030000e+03,
       1.9000000e+01, 7.4000000e+01, 3.1147541e-01, 4.7500000e+00])

In [ ]:
# Creating a Pipeline of tasks 

# Using Pipeline Class 
from sklearn.pipeline import Pipeline

# Using the StandardScaler to scale all the numerical attributes 
from sklearn.preprocessing import StandardScaler

numerics = ["float64", "int64"]

num_data = data_tr.select_dtypes(include = numerics)

# pipeline for numerical attributes 
# imputing  -> adding attributes  -> scale them

num_pipeline = Pipeline([
                         ("imputer", SimpleImputer(strategy = "median")), 
                         ("attrs_adder", CustomAttrAdder()), 
                         ("std_scaler", StandardScaler()),
])

num_data_tr = num_pipeline.fit_transform(num_data)
num_data_tr[0]

array([-0.85657842, -1.07804475, -1.15192977, -1.17220298,  1.21586943,
       -0.54436373,  1.70952741,  1.29565517])

In [ ]:
# Transform different columns or subsets using ColumnTransformer 
from sklearn.compose import ColumnTransformer

num_attrs = list(num_data)
cat_attrs = ["Origin"]

# complete pipeline to transform
# both numerical and categorical attributes 

full_pipeline = ColumnTransformer([
                                   ("num", num_pipeline, num_attrs), 
                                   ("cat", OneHotEncoder(), cat_attrs), 
])

prepared_data = full_pipeline.fit_transform(data)
prepared_data

array([[-0.85657842, -1.07804475, -1.15192977, ...,  1.        ,
         0.        ,  0.        ],
       [-0.85657842, -1.1174582 , -0.9900351 , ...,  0.        ,
         0.        ,  1.        ],
       [-0.85657842, -0.3587492 , -0.31547399, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.85657842, -0.56566984, -0.53133355, ...,  0.        ,
         1.        ,  0.        ],
       [-0.85657842, -0.78244384, -0.23452666, ...,  1.        ,
         0.        ,  0.        ],
       [ 0.32260746, -0.45728283,  0.44003446, ...,  1.        ,
         0.        ,  0.        ]])